### PR TITLE
add GetFullPageScreenShot() func

### PR DESCRIPTION
**Pull request by s3rj1k**
GetFullPageScreenShot() creates full sized screenshot of the currently loaded page

### CODE REVIEW

**Comment by s3rj1k** [comment]
bump @wirepair 
Can this be merged?

**Comment by wirepair** [comment]
Hey @s3rj1k i need a test case to make sure it works. Maybe create a testcase html page with a single dot in the middle, take a picture, ensure it's accurate, then md5sum it. Then have the unit test do the same test and compare the image hashes?

**Comment by s3rj1k** [comment]
@wirepair add test for GetFullPageScreenShot()
can you review pull request?

**Comment by wirepair** [comment]
Hey @s3rj1k i fixed up your patch a bit and pushed a change to your PR. Did you even try it? You had some statements that would not even compile for me.

**Comment by s3rj1k** [comment]
@wirepair.  Sorry I do not see any PR from you. 
Strange it would not compile for you. The actual screenshot func is battletested. 
I admit that tests may be a bit off

**Comment by s3rj1k** [comment]
@wirepair fixed test data type issue, should now compile, sorry for that

**Comment by s3rj1k** [comment]
Bump

**Comment by wirepair** [comment]
Hey @s3rj1k ,
Unfortunately it doesn't appear this patch works as I'd expect it to, when I took a screenshot i see the scroll bars inside the image:
data_test. Also there's still a few outstanding things in the test case you didn't address (different window giving different hash results). Not sure why my PR isn't showing up for you but here's the diff, which i modified a bit to try out setting various window sizes, but i still was unable to get rid of that scroll bar. If you can figure that out and address the other issues with the test I'll accept.
Here's my attempt at getting it working, maybe it'll give you some ideas:
```Go
func TestTabFullPageScreenShot(t *testing.T) {
	originalHash, err := hex.DecodeString("6ec6e58eba257ad1f81f947f67fc66ab")
	if err != nil {
		t.Fatalf("invalid original hash value: %s\n", err)
	}

	testAuto := testDefaultStartup(t)
	defer testAuto.Shutdown()

	tab, err := testAuto.NewTab()
	defer testAuto.CloseTab(tab)
	if err != nil {
		t.Fatalf("error getting tab")
	}

	if _, errorText, err := tab.Navigate(testServerAddr + "background.html"); err != nil {
		t.Fatalf("error navigating: %s %s\n", errorText, err)
	}

	_, _, rect, err := tab.Page.GetLayoutMetrics()
	if err != nil {
		t.Fatalf("error getting page layout metrics\n")
	}

	windowID, _, err := tab.Browser.GetWindowForTargetWithParams(&gcdapi.BrowserGetWindowForTargetParams{TargetId: tab.ChromeTarget.Target.Id})
	if err != nil {
		t.Fatalf("error getting windowId for target (%s), %s\n", tab.ChromeTarget.Target.Id, err)
	}

	browserBounds := &gcdapi.BrowserBounds{Left: 0, Top: 0, Width: int(rect.Width), Height: int(rect.Height), WindowState: "fullscreen"}
	browserParams := &gcdapi.BrowserSetWindowBoundsParams{WindowId: windowID, Bounds: browserBounds}

	if _, err := tab.Browser.SetWindowBoundsWithParams(browserParams); err != nil {
		t.Fatalf("failed to set browser bounds: %s\n", err)
	}

	tab.WaitStable()

	data, err := tab.GetFullPageScreenShot()
	if err != nil {
		t.Fatalf("error making full page screenshot: %s\n", err)
	}

	newHash := md5.Sum(data)
	if !bytes.Equal(newHash[:], originalHash) {
		t.Fatalf("error, MD5 for full page screenshot %x does not match predefined value: %x\n", newHash[:], originalHash)
	}

}
```

**Comment by s3rj1k** [comment]
@wirepair 

Hi, a see the issue, you are not using chrome headless mode in test environment.
Adding those two flags: `--headless --hide-scrollbars` fixes issue with scrollbars.

This is an upstream [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=679343) related to BrowserContexts.

If one to look how google is doing fullpage screenshots using their [puppeteer](https://github.com/GoogleChrome/puppeteer/blob/f5bb333cd0c42306f47e7767e5cb8b78af557c27/lib/Launcher.js#L83)
they also do this in headless mode.

In my opinion we can just add comments to GetFullPageScreenShot function that it only works correctly in headless mode or even add some checking if not headless return error.

As with different md5 hashes, this occurs do to scrollbars, this one also should be fixed in headless mode.

I really hope that this is enough data to accept PR otherwise i would have to switch to another CDP library, this is not a desired outcome.

**Comment by wirepair** [comment]
Ah that makes sense, so we could just create a testHeadlessStartup() that instead of testDefaultStartup() will add the additional flags prior to launching the browser. Unfortunately I will be traveling this week so I won't be able to do much on this.

**Comment by s3rj1k** [comment]
any update on this?

**Comment by wirepair** [comment]
Hey @s3rj1k sorry for the delay I was traveling for a while, but was finally able to get your patch merged. I created and merged a different branch since I had to add a lot to the test case. Let me know if you have any problems.

**Pull request closed without merging**
