### PR TITLE
Adding Element.SetAttributeValue

### PR DESCRIPTION
**Pull request by kenshaw**
This is useful if you need to modify an element's attribute on the actual DOM.

### CODE REVIEW

**Comment by wirepair** [comment]
would you mind adding to the element_test.go a test case for this?

**Comment by kenshaw** [comment]
Yes, will do so. But will need a bit of time, as I'm working on some other code at the moment. Thanks!

**Comment by kenshaw** [comment]
Sorry for the delay in adding the element test. Been a bit busy with other things. Please review and let me know if this is adequate. Thanks!

**Comment by wirepair** [comment]
looks good, thanks!

**Pull request merged**
