### PR TITLE
A method to get all elements that match a xpath or CSS selector 

### PR DESCRIPTION
**Pull request by patanasov**
Here is my suggestion for extending **type Tab** with a method to get all elements that match a xpath or CSS selector.
I used the **gcdapi WithParams** for more consistency and reliability. I suggest a simple unit test also.

### CODE REVIEW

**Comment by wirepair** [comment]
Any progress on the comments in the review?

**Comment by patanasov** [comment]
I will do my best to make it this week :-)

**Comment by wirepair** [comment]
Sounds good, I'll hold off on updating gcd to the latest protocol specs until it's complete. Otherwise you'd have to refactor again if any APIs changed.

**Comment by patanasov** [comment]
@wirepair, now it should be good to go. 
PS: sorry for the slow action on the PR

**Pull request merged**
