### PR TITLE
add a way to connect to instance

### PR DESCRIPTION
**Pull request by davyzhang**
works fine with example

### CODE REVIEW

**Comment by wirepair** [comment]
Hey @davyzhang thanks for the PR, but I don't see any code handling shutdown/closing of autogcd when this option is enabled. Also can you add unit tests and make sure all tests pass?

**Comment by davyzhang** [comment]
In my use case, I started a headless chrome docker to scrap some pages periodically, and I want to keep this docker running and receiving internal connections. So I didn't think about shutdown/closing operation. Since you have brought it up, I might rethink of this feature

**Comment by wirepair** [comment]
Yeah, I think it's a great feature to add it just needs all use cases covered. If you want to close this and open a new one once you are ready that may be the best way moving forward. For a unit test it should be simple to have the test case start up an external chromium process (on the same machine) outside of the autogcd.Start method.

**Comment by davyzhang** [comment]
Ok, I will try to add some unittest then

**Comment by davyzhang** [comment]
Hi, @wirepair I can't figure out a way to do full cover test except rewriting every test function with instance start again. Any suggestion?

Here I have a manually start up chrome with random debug port:
```golang
func testInstanceStartup(t *testing.T) *AutoGcd {
	// ta := testDefaultStartup(t)
	port := testRandomPort(t)
	userDir := testRandomDir(t)
	flags := append(testStartupFlags, fmt.Sprintf("--remote-debugging-port=%s", port))
	flags = append(flags, fmt.Sprintf("--user-data-dir=%s", userDir))
	cmd := exec.Command(testPath, flags...)
	err := cmd.Start()
	if err != nil {
		log.Printf("start chrome ret err %+v", err)
		return nil
	}
	s := NewSettings("", "")

	s.SetInstance("localhost", port)

	auto := NewAutoGcd(s)
	auto.Start()
	if err := auto.Start(); err != nil {
		t.Fatalf("failed to start chrome: %s\n", err)
	}
	auto.SetTerminationHandler(nil) // do not want our tests to panic
	return auto
}

```
here's an example how to test with getTab function
```golang
func TestInstanceGetTab(t *testing.T) {
	var err error
	var tab *Tab
	auto := testInstanceStartup(t)
	defer auto.Shutdown() //no effect

	tab, err = auto.GetTab()
	if err != nil {
		t.Fatalf("Error getting tab: %s\n", err)
	}

	if tab.Target.Type != "page" {
		t.Fatalf("Got tab but wasn't of type Page")
	}
}
```

So do I suppose to do all of these by replacing testDefaultStartup to testInstanceStartup in every test function?

**Comment by wirepair** [comment]
Hmm, I don't think you need to modify/run all tests with the specific ConnectToInstance version. Just create tests that cover starting and stopping using ConnectToInstance. Then just run the tests that already exist to make sure your changes don't break any of them. Sorry for not being more clear.

**Pull request closed without merging**
